### ISSUE TITLE
Systematically link to Open Data Portal (from chart information and tracker boxes)

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5353] opened 2021-09-22 23:07 UTC
Still to do:

- [x] review gaps and assumptions in Mchael's spreadsheet
- [ ] Explore rationale for our partially duplicative data dictionary entries

Needs some exploration.

Here is [how SF does it. ](https://sf.gov/data/covid-19-cases-and-deaths)
<img width="778" alt="Screen Shot 2021-09-23 at 1 14 43 PM" src="https://user-images.githubusercontent.com/9556188/134577725-f4e3827f-732b-4163-9cb8-2d03790be635.png">

**Comment by abquirarte** [comment] 2021-09-22 23:11
FWIW- I made this ask :) 

Currently we bury links to the open data versions of our data dashboards/charts. As best practice, I'd like to have a link to the open data of each viz close to the visualization.

**Comment by m-sullivan7** [comment] 2021-10-07 17:01
Off the top of my head, this may be as simple as putting a link in the _Chart information_ drawers. I look forward to talking about it!

**Comment by mediajunkie** [comment] 2021-10-07 18:29
That may well do the trick, and we could mock it up for discussion and review.

For the sake of argument let's consider how we might make the affordance visible by default without additional exploration required, as a further constraint.

**Comment by m-sullivan7** [comment] 2021-10-07 21:22
I'd benefit from some coordination before I mock something up to:

- Identify the charts affected (I think this is every chart?)
- The data source to link to from that chart
- What you mean by "affordance"--new term for me!

**Comment by m-sullivan7** [comment] 2021-10-08 20:24
Here's a [spreadsheet of all our charts](https://docs.google.com/spreadsheets/d/1pCYn_COc16VLmJmex9AF3eCLvsa_iAaOm5EuSkWAzng/edit?usp=sharing) (plus a question about whether to include one map) with my best guesses as to what data source backs each up. Where I didn't have a good guess I left it blank.

@mediajunkie If you can fill any gaps and/or confirm my guesses, I'd love your assistance!

**Comment by m-sullivan7** [comment] 2021-10-11 23:25
[Vaccination progress data](https://covid19.ca.gov/vaccination-progress-data/) has been published with data sources. I will alert engineers to look at the column width of the last three columns where it looks like the data source note extends to the left of the chart.

I will work on state dashboard and health equity tomorrow.

**Comment by abquirarte** [comment] 2021-10-11 23:34
Thank you @m-sullivan7! 😄

**Comment by m-sullivan7** [comment] 2021-11-09 18:57
[Data and tools](https://covid19.ca.gov/data-and-tools/) is live. Jim is investigating getting a couple of links in the health equity page in the right place. Content is mostly staged and ready to go.

**Comment by m-sullivan7** [comment] 2021-11-09 19:58
[Health equity](https://covid19.ca.gov/equity/) is live too now.

That leaves just one source data link missing @mediajunkie: the [Positivity rate in California/county](https://covid19.ca.gov/state-dashboard/#county-statewide) chart. I suspect that it's the same data as the neighboring chart, _Total tests in California/county_. If they use the same source data, it's an easy content fix to make the existing link cover both charts.

Do we want to continue the bigger _Data and tools_ discussion in this issue or create a new issue so this issue can be closed (since the original purpose will be fulfilled)?

**Comment by mediajunkie** [comment] 2021-11-09 21:10
It does appear that the same source that gives the total number of tests
per county also gives the number of positive tests, so maybe the question
to confirm with @jbum is whether that ratio is the source of the positivity
rate we report, or if it we have another source that is documented
elsewhere in the ODP.

**Comment by m-sullivan7** [comment] 2021-11-10 00:37
Thanks for the initial look! I'll wait for final confirmation from @jbum before preparing a quick edit for state dashboard.

**Comment by m-sullivan7** [comment] 2021-11-11 00:42
@mediajunkie I confirmed with Jim that the charts use the same source data. I drafted [this content update](https://docs.google.com/document/d/1Z0-5SQOR_6Uhuqh36M8smVgQNki_xs1uOiJsUOIR3j0/edit?usp=sharing) to cover off our last piece of source data documentation. OK to publish?

I also updated [our spreadsheet](https://docs.google.com/spreadsheets/d/1pCYn_COc16VLmJmex9AF3eCLvsa_iAaOm5EuSkWAzng/edit?usp=sharing) with this last piece.

**Comment by mediajunkie** [comment] 2021-11-11 00:52
Yes, please!

**Comment by m-sullivan7** [comment] 2021-11-12 19:20
The final source data link is on [state dashboard](https://covid19.ca.gov/state-dashboard/#county-statewide). Do we want to have the Data and tools overhaul on this ticket or will we close this one and move that to a new ticket?

**Comment by mediajunkie** [comment] 2021-11-12 19:41
new ticket, in backlog
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Closed** 2021-11-12 19:41 UTC
Labels: Content update
