### ISSUE TITLE
DESIGN: It’s unclear what positive rate really means. Does it mean people that got tested were positive?

### ISSUE THREAD

**Issue by clarita1980** [cagov/covid19#1823] opened 2020-09-28 18:28 UTC
Make the information accessible (is hidden next to the positive case next to map, when you hover)

**Comment by m-sullivan7** [comment] 2020-09-28 22:56
Content in WordPress does not currently define "positivity rate". This includes the matrix and questions and answers at the bottom of the page.

A definition is provided by the map hover over box when placing the cursor over the positivity rate number to the left of the selectable county map. It is defined as: "7-day average of positive lab-confirmed COVID-19 tests divided by total tests with conclusive results."
![Map hoverover](https://user-images.githubusercontent.com/69169190/94494064-15161d80-01a3-11eb-9863-936bf5437073.png)
This definition was likely added after the user research was conducted, so participants may not have had this option available to them.

@hannahslee, should we pursue additional updates to the page to define the positivity rate elsewhere?

**Comment by m-sullivan7** [comment] 2020-09-28 23:07
Per @hannahslee, pursue both a better worded definition and making it more prominent.

**Comment by m-sullivan7** [comment] 2020-09-30 16:40
@adam-little I'd appreciate a design perspective (when convenient) on how to make the definition of positivity rate more prominent on the [Blueprint page](https://covid19.ca.gov/safer-economy/). My draft idea is to work in the matrix since that puts the information closest to where readers will need it, but I welcome other ideas!

I'm working on a shorter and clearer definition than what's in the map hoverover, but I wouldn't be surprised if we run my idea by CDPH for approval first.

No deadline on this to my knowledge, other than it's a P1 that, depending on the solution, may not require engineering as I can edit the matrix to a limited degree.

**Comment by m-sullivan7** [comment] 2020-09-30 16:56
[Working space for new definition.](https://docs.google.com/document/d/1CScl4j4siEelnC2uNM0y2ve2sisKHi2LTl3wrOxYUJo/edit?usp=sharing)

**Comment by adam-little** [comment] 2020-09-30 19:37
@m-sullivan7 I think that's the obvious solution. Something like this: 
![image](https://user-images.githubusercontent.com/69167298/94731431-9c859d00-0319-11eb-8659-dada7725c35d.png)

If we add a definition for the positivity rate, do we then need one for Adjusted cases? 

I would love to take a second pass at this entire matrix.

**Comment by m-sullivan7** [comment] 2020-09-30 22:42
@adam-little Awesome! Glad to know I was on the right track!

I think a second pass on the matrix as a whole would be great. Defining adjusted case rate is also a good idea. I'll add that to my working doc and see what I can come up with.

**Comment by m-sullivan7** [comment] 2020-10-01 23:16
@adam-little after scribbling and working with @thepegisin, here's the draft definitions for each term we propose:

- Adjusted case rate: 7-day average of COVID-19 cases per 100,000, adjusted for number of tests performed
- Positivity rate: 7-day average of all COVID-19 tests performed that are positive

Use away for any new designs you do!

**Comment by m-sullivan7** [comment] 2020-10-02 15:53
For documentation, here's some per page feedback from Blueprint supporting making this change:
9/30/2020 7:01:57 AM: Please clarify the “positivity” rate. The website alludes that it is a percentage of the population, while in fact it is the percentage of tests taken, not the percentage of actual population. Statistically, the number being presented as a percentage of the population is not correct. That needs to be clearly communicated and explained in terms of how the number is calculated.

**Comment by adam-little** [comment] 2020-10-06 22:54
@kenbasart Can we assign this to a developer?

Proposed solution: Add "Adjusted case rate" and ""Positivity rate" definitions to the matrix on the Blue print page.

Adjusted case rate: 7-day average of COVID-19 cases per 100,000, adjusted for number of tests performed
Positivity rate: 7-day average of all COVID-19 tests performed that are positive

![Group 30](https://user-images.githubusercontent.com/69167298/95268413-4925ba00-0805-11eb-9744-5f4f71ff40fb.png)

[Link to Figma](https://www.figma.com/file/LrzsOu8U5KcMAjJTQ1O3BG/covid19.ca.gov-screens?node-id=276%3A1092)

**Comment by m-sullivan7** [comment] 2020-10-06 22:56
There's a _chance_ that content might be able to do it. Want me to try before we involve developers?

**Comment by kenbasart** [comment] 2020-10-06 22:57
Yes go for it Michael

**Comment by m-sullivan7** [comment] 2020-10-06 23:17
Good news: in theory, content could do this!
Less good news: we probably need some help (which may require developers) to style the text. They're doing some cool things to style the text that probably need tweaking.
![image](https://user-images.githubusercontent.com/69169190/95269977-6f405f80-07ef-11eb-82eb-4a97e403ced1.png)

**Comment by kenbasart** [comment] 2020-10-06 23:24
Ok let's talk to them tomorrow when Aaron gets back.

**Comment by kenbasart** [comment] 2020-10-30 22:18
Addressed with new design of matrix.

**Closed by kenbasart** 2020-10-30 22:18 UTC
Labels: Dimmer Switch, P1
